### ISSUE TITLE
Expression type Convert not supported for getLinkTarget expression

### ISSUE THREAD

**Issue by fynnen** [cbcrc/LinkIt#10]
For the methods various load methods (loadlinkbyid, loadlinkfrommodel, etc), the getLinkTarget expression cannot be a convert ExpressionType, only a parameter ExpressionType. 

This prevents the use of generics and interfaces as a LinkedSource (mostly in extension methods).

# Suggested solution
Support convert ExpressionType for the getLinkTarget expression.

**Comment by fynnen** [comment]
`
        public static LoadLinkProtocolForLinkedSourceBuilder<TLinkedSource> LoadLinkForInterface<TLinkedSource, TModel>(
            this LoadLinkProtocolForLinkedSourceBuilder<TLinkedSource> loadLinkProtocolForILinkedSourceBuilder)
            where TLinkedSource : ILinkedSource, IInterface<TModel>
            where TModel : IModel
        {
            loadLinkProtocolForILinkedSourceBuilder
                .LoadLinkReferenceById(
                    linkedSource => linkedSource.Model.FieldIdNonConventionName,
                    linkedSource => linkedSource.Field
                );

            return loadLinkProtocolForILinkedSourceBuilder;
        }

        public interface IInterface<T> where T : IModel
        {
            T Model { get; set;}
            object Field { get; set;}
        }
        public interface IModel
        {
            int FieldIdNonConventionName { get; set; }
        }`

Seems like it should work, but .net creates a convert Expression to access the value since internally it will need to cast  at runtime.

**Comment by laurentlbm-rc** [comment]
Merged
