### ISSUE TITLE
Provide information to aid in debugging load-link operations

### ISSUE THREAD

**Issue by laurentlbm-rc** [cbcrc/LinkIt#8]
It is sometimes hard to debug load-link operations. It would be useful to have some information to help debugging when `IReferenceLoader.LoadReferencesAsync()` is called and when the operation is finished.

### Propostion:

1. Create a new object to include information about a load-link operation: `ILoadLinkDetails`. It would include the following details:
   - `LinkedSourceType`: Type of the linked source being load-linked.
   - `LinkedSourceModelType`: Type of the model of the linked source being load-linked.
   - `Result`: List of linked sources (or partial linked sources) currently loaded.
   - `Took`: Time it took to load and link everything. _Only available at the end._
   - ~~`LoadingLevels`~~`Steps`: List of levels/steps of loading & linking required with information about the operation.
     - ~~`Level` or~~ `StepNumber`
     - `References`: Information about the references to load at this level:
       - `Type`: Type of reference.
       - `Ids`: IDs to load for this reference type, at this level (same info that's already in the `ILoadingContext`). _Will not be available for future steps._
       - `Values`: Reference values loaded. _Will not be available for current or future steps._
     - `LoadTook`: Time it took to load all reference types for this level. _Will not be available for current or future steps._
     - `LinkTook`: Time it took to link all references and linked sources for this level. _Will not be available for current or future steps._
   - ~~`CurrentlyLoading`~~`CurrentStep`: Value from `Steps` for the current loading operation.
   - ~~`Source`~~`CallDetails`: Object showing how the load-link was started.
     - ~~`LoadedFrom`~~`Method`: Method called: ByIdAsync, ByIdsAsync, FromModelAsync, FromModelsAsync
     - `Values`: Values supplied at the start of the load-link (list of ids or models).
1. Add a property `ILoadingContext.LoadLinkDetails` that will include the `ILoadLinkDetails` for the current load-link operation. This property will only be set if "debug mode" is enabled.
1. ~~Add a flag to enable debug info: `ILoadLinkProtocol.EnableDebugMode()`.~~

### Questions
1. A load-link operation returns one or multiple linked sources, so how do we get the `ILoadLinkDetails` object when the operation is finished? Options:
   1. Add new methods to use instead of `FromModel[s]Async()`/`ById[s]Async()` to return both linked sources and`ILoadLinkDetails`. For example:
      ```csharp
      var response = loadLinkProtocol.LoadLink<RootLinkedSource>.WithDebugInfo().FromModelsAsync(models);
      IList<RootLinkedSource> linkedSources = response.Result;
      ILoadLinkDetails loadLinkDetails = response.LoadLinkDetails;
      ```
   1. Add an optional callback param of type `Action<ILoadLinkDetails>` to `FromModel[s]Async()`/`ById[s]Async()` so that the caller can inspect the details. For example:
      ```csharp
      var linkedSources = loadLinkProtocol.LoadLink<RootLinkedSource>.FromModelsAsync(models, details => {
         Logger.Log(details);
      });
      ```

**Comment by fcharest** [comment]
Should `ILoadLinkProtocol.Statistics` object be used in that case?

**Comment by fcharest** [comment]
Also, for time taken, is it possible to split `load` times and `link` times? After a bit of testing, I found that about 10% of the time is taken by linking data.

**Comment by laurentlbm-rc** [comment]
Using `ILoadLinkProtocol.Statistics` would be problematic because of threads and concurrency. How would you get info on the current op?
